version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=TareasDb
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidvz.code@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver_data:/var/opt/mssql
  